import type { Game } from './types';

export const STATIC_GAMES: Game[] = [
  {
    id: 1,
    rank: 1,
    title: 'Elden Ring',
    category: 'Action / Souls-like',
    size_gb: 60,
    accent: '#D9FFF4',
    status: 'Platinum',
    nsfw: false,
  },
  {
    id: 2,
    rank: 2,
    title: 'The Legend of Zelda: Tears of the Kingdom',
    category: 'Open World / Adventure',
    size_gb: 16,
    accent: '#EEF8CD',
    status: 'Completed',
    nsfw: false,
  },
  {
    id: 3,
    rank: 3,
    title: 'DOOM Eternal',
    category: 'Shooters / FPS',
    size_gb: 80,
    accent: '#FFC5AA',
    status: 'Platinum',
    nsfw: false,
  },
  {
    id: 4,
    rank: 4,
    title: 'The Last of Us Part II',
    category: 'Narrative / Story-Driven',
    size_gb: 100,
    accent: '#D9FFF4',
    status: 'Completed',
    nsfw: true,
  },
  {
    id: 5,
    rank: 5,
    title: 'Forza Horizon 5',
    category: 'Racing / Sports',
    size_gb: 110,
    accent: '#EEF8CD',
    status: 'Platinum',
    nsfw: false,
  },
  {
    id: 6,
    rank: 6,
    title: 'Baldur\'s Gate 3',
    category: 'Action-Adventure / Misc',
    size_gb: 150,
    accent: '#FFC5AA',
    status: 'Playing',
    nsfw: false,
  },
];